apiVersion: apps/v1
kind: Deployment
metadata: 
  generation: 1
  labels:
    app: nginx-multitool
  name: nginx-multitool
  namespace: test 
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-multitool 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-multitool
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent 
        name: nginx  
        ports:
        - containerPort: 80
          name: http-port 
      - image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent 
        name: multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1180
          name: http-port
        - containerPort: 11443
          name: https-port
      dnsPolicy: ClusterFirst
      restartPolicy: Always  
      terminationGracePeriodSeconds: 30