apiVersion: v1
kind: Service 
metadata: 
  labels:
    app: nginx
  name: nginxservice
  namespace: test 
spec:  
  ports:
  - nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
    name: http-port
  selector:
    app: nginx 
  type: NodePort