apiVersion: v1
kind: Service 
metadata: 
  labels:
    app: nginx-multitool
  name: nginx-multitool
  namespace: test 
spec:  
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
    name: http-port
  - nodePort: 30443
    port: 11443
    protocol: TCP
    targetPort: 11443
    name: https-multitool
  - nodePort: 30080
    port: 1180
    protocol: TCP
    targetPort: 1180
    name: http-multitool
  selector:
    app: nginx-multitool 
  type: NodePort